apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: converter
  template:
    metadata:
      labels:
        components: converter
    spec:
      containers:
        - name: converter
          image: antonlarichev/conv-service:1.0
          ports:
            - containerPort: 4000
          env:
            - name:  AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name:  secretforconv
                  key:  AMQP_EXCHANGE
            - name:  AMQP_USER
              valueFrom:
                secretKeyRef:
                  name:  secretforconv
                  key:  AMQP_USER
            - name:  AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  secretforconv
                  key:  AMQP_PASSWORD
            - name:  AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name:  secretforconv
                  key:  AMQP_HOSTNAME
            - name:  AMQP_QUEUE
              valueFrom:
                secretKeyRef:
                  name:  secretforconv
                  key:  AMQP_QUEUE
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
