apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: rabbitmq
  template:
    metadata:
      labels:
        components: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3.13.7
          name: rabbitmq
          ports:
            - containerPort: 5672
          env:
            - name: SEED_USERNAME
              value: rmq
            - name: SEED_USER_PASSWORD
              value: rmq
          resources:
            limits:
              cpu: "400m"
              memory: "500M"