apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-clusterip
spec:
  selector:
    components: {{ .Values.app.components }}
  type: ClusterIP
  ports:
  - port: {{ .Values.app.port }}
    protocol: TCP